  name: Build using esy

  on:
    pull_request:
    push:
      branches:
        - main

  jobs:
    linux:
      runs-on: ubuntu-latest

      services:
        pg:
          image: postgres:14
          env: POSTGRES_USER: postgres POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 10
          ports:
            - 5432:5432
          volumes:
            - /var/run/postgresql:/var/run/postgresql

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - name: Check formatted
        run: esy check-formatted

      - name: Run tests
        run: esy test
