  name: "Build using Nix"
  on:
    pull_request:
    push:
      branches:
        - main
  jobs:
    linux:
    services:
      pg:
        image: postgres:14
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
        volumes:
          - /var/run/postgresql:/var/run/postgresql
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          ocamlVersion: [4_12, 4_13]
      steps:
        - uses: actions/checkout@v2
        - uses: cachix/install-nix-action@v14
        - uses: cachix/cachix-action@v10
          with:
            name: hermes-ci
            authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        - name: "Run nix build"
          run: nix-build ./nix/ci/test.nix --argstr ocamlVersion ${{ matrix.ocamlVersion }}
